### ISSUE TITLE
Tree view doesn't work with properties containing object

### ISSUE THREAD

**Issue by obenjiro** [discoveryjs/discovery#11]
Data
```
[{ id: 1, a: { id: 3, val: 1 }}, { id: 2, b: [{ id: 4, val: 1 }]}]
```

View
```
{
    view: 'tree',
    children: 'a or b',
    item: [
    	'text:id', 'struct'
    ],
    expanded: 100
}
```

**Actual Result**
<img width="203" alt="2019-02-21 12 54 36" src="https://user-images.githubusercontent.com/1760346/53159908-e05ddf80-35d7-11e9-8d2b-66adcf8ea505.png">

**Expected**
To see object with id 3 in tree

**Comment by aiboy** [comment]
Workaround that I have found. At least for now

```
{
    view: 'tree',
    data: '',
    children: '$r: (a or b) + []; $r.[size() > 1]',
    item: [
    	'text:id', 'struct'
    ],
    expanded: 100
}
```

<img width="223" alt="2019-02-21 13 19 57" src="https://user-images.githubusercontent.com/1760346/53161636-6891b400-35db-11e9-9473-7ddca65b4f78.png">

**Comment by lahmatiy** [comment]
One more workaround `(a or b or []) + []`

**Comment by lahmatiy** [comment]
A solution from 2024: `a or b | is array ?:? [$]` (or the full form: `a or b | is array ? $ : ($ ? [$] : undefined)`)
More solutions:
- `a or b | is object ? [$] : $`
- `[...a or b].[]` (creates temporary array)
- `a or b |? [...]` or full form `a or b | $ ? [...$] : $` (creates temporary array)

**Comment by obenjiro** [comment]
Thanks, I think that will be enough for now.
