### ISSUE TITLE
Allow multiple Jora requests in one edit box

### ISSUE THREAD

**Issue by rualark** [discoveryjs/discovery#35]
On separate lines.

**Comment by lahmatiy** [comment]
Could you please explain a use case?

**Comment by rualark** [comment]
Example: working with large JSON, need to select from different lists and objects, compare results or create a screenshot which shows how data compares.

E.g. I work with 1-5 Mbyte json every day.

**Comment by lahmatiy** [comment]
But why it should be on separate lines? I guess it should be different query editors with their own outputs, isn't it? If so, I'm working on new report page where that's will be possible, unfortunately can't say ETA for this feature.
One of solutions is to build an object with various computations, and you also may use variables, e.g.
```
$foo: foo + bar.({ ... });
$bar: a.b.c.d;
{
  $foo,
  $bar,
  baz: something.cool().[...]
}
```

**Comment by rualark** [comment]
Are there examples to understand it better?
How can I query two different objects inside json in one report?

**Comment by lahmatiy** [comment]
Can you provide more details about the problem?
You can make an object with necessary computations like so:
```
{
  foo: some.path.(map).[filter].etc,
  bar: another.query
}
```
And then use it for views
```
[
  'table:foo', // the same as { view: 'table', data: 'foo' }
  'struct:bar'
]
```
Or use queries right in view configuration:
```
[
  'table:some.path.(map).[filter].etc', // the same as { view: 'table', data: 'some.path.(map).[filter].etc' }
  'struct:another.query'
]
```

**Comment by rualark** [comment]
Thanks. In this case multiple jora requests are not needed.
But it would be cool to save report templates.
