### ISSUE TITLE
Some JSON is not parsed successfully

### ISSUE THREAD

**Issue by rualark** [discoveryjs/discovery#48]
Unfortunately, today I found JSON which is not parsed by JsonDiscovery at all. This JSON is parsed successfully by Visual Studio Code.

This big json is not much different from all the other big jsons that I used to parse with JsonDiscovery successfully.

Unfortunately, I cannot provide this json and it is too big to replace sensitive data (2 megabytes). But if you add some debugging logs to plugin, I will be able to see mistakes where parsing failed.

**Comment by lahmatiy** [comment]
We are found the root cause of the problem (yeah, finally!). It's already fixed and waiting for publishing to stores.
See details in [JsonDiscovery issue](https://github.com/discoveryjs/browser-extension-json-discovery/issues/82).
