### ISSUE TITLE
Support Set and Map

### ISSUE THREAD

**Issue by smelukov** [discoveryjs/discovery#62]
**Data:**
```js
{
  foo: new Set([{bar: 1 }, {bar: 2 }, {bar: 3 }]),
  baz: new Map([[quux: [1, 2, 3]]])
}
```

Queries:
- `foo.[bar > 2]`
- `baz.quux.[$ > 2]`

**Comment by lahmatiy** [comment]
That's a subject for [jora](https://github.com/discoveryjs/jora) query language
