### ISSUE TITLE
Feature Request: Ability to provide variable ahead of time

### ISSUE THREAD

**Issue by aiboy** [discoveryjs/discovery#8]
Something that looks like this:

prepare.js
```
discovery.addVariables({
     '$a': '<($.a.b)>'
})
```

discovery ui
```
[{ a: { b: 1 } }].map($a)   // will return [1]
```

This will help to create Domain Specific Queries and it will save a lot of time for monotonous jobs.

**Comment by lahmatiy** [comment]
Maybe `discovery.addQueryHelpers()` is what you are requesting for?

```js
discovery.addQueryHelpers({
   foo: current => discovery.query('$.a.b', current)
});
```
Usage:
```
[{ a: { b: 1 } }].foo()
```

**Comment by aiboy** [comment]
That's solves issue for now, but there is no autocomplete for functions :/

**Comment by lahmatiy** [comment]
Ok, closing the issue then.
> there is no autocomplete for functions
That's will be added in future releases. Can you fill a separate issue for this feature?
