### ISSUE TITLE
Information unknown

### ISSUE THREAD

**Issue by sebatro** [discoveryjs/discovery#81]
I get a lots of log entries for missing values I should report to the developer.
If required I could send also a pictures of the meter itself, its a new model, installed today.

[iobroker.2021-03-29.log](https://github.com/discoveryjs/discovery/files/6223985/iobroker.2021-03-29.log)

**Comment by lahmatiy** [comment]
@sebatro Those errors are not related to this project (`Discovery.js`) but from `discovergy` (note extra `g` before `y`). You should send the log to its tracker.
